### ISSUE TITLE
Build dependencies in pyproject.toml

### ISSUE THREAD

**Issue by MuellerSeb** [GeoStat-Framework/GSTools#152]
Up to now, people installing GSTools from source (for openmp support for example) need to provide cython and numpy in beforehand.

We could overcome this by providing a `pyproject.toml` which was specified for this exact reason:

```toml
[build-system]
requires = [
    "setuptools>=42", 
    "wheel", 
    "setuptools_scm[toml]>=3.5", 
    "numpy>=1.14.5,<2.0", 
    "Cython>=0.28.3,<3.0"
]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
source = ["gstools"]
omit = ["*docs*", "*examples*", "*tests*", "*/gstools/covmodel/plot.py", "*/gstools/field/plot.py"]

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "def __repr__", "def __str__"]

[tool.black]
line-length = 79
target-version = ["py37"]
```

See:
- https://scikit-hep.org/developer/packaging
- https://snarky.ca/what-the-heck-is-pyproject-toml/
- https://levelup.gitconnected.com/how-to-deploy-a-cython-package-to-pypi-8217a6581f09
- https://github.com/pypa/setuptools_scm/blob/main/README.rst#pyprojecttoml-usage
- https://www.github.com/pypa/sampleproject/tree/main/MANIFEST.in
- https://cibuildwheel.readthedocs.io/en/latest/options/#before-build
- https://github.com/readthedocs/readthedocs.org/issues/7030
  - https://github.com/nschloe/meshplex/blob/main/.readthedocs.yml
  - https://docs.readthedocs.io/en/stable/config-file/v2.html#migrating-from-the-web-interface
- https://black.readthedocs.io/en/stable/pyproject_toml.html#
- https://coverage.readthedocs.io/en/coverage-5.0.4/config.html
- https://stackoverflow.com/questions/60084128/does-description-file-in-setup-cfg-section-metadata-have-any-effect
- https://stackoverflow.com/a/66443941
- https://stackoverflow.com/a/45549526/6696397
