### ISSUE TITLE
Declaring build dependencies

### ISSUE THREAD

**Issue by jonathf** [GeoStat-Framework/GSTools#153]
Installing gstools with pip in a clean python environment causes en error. Typically something like `ModuleNotFoundError: No module named 'Cython'`.
Would you consider adding a minimal `pyproject.toml` file as specified in [PEP 518](https://www.python.org/dev/peps/pep-0518/), defining gstools' build dependencies. Something like:
```toml
[build-system]
requires = ["setuptools", "wheel", "Cython", "numpy"]
```
